export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

//---- auth -----//
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER';

//---- property (not being used, possible future implementation) -----//
export const CREATE_PROPERTY_BEGIN = 'CREATE_PROPERTY_BEGIN'
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS'
export const CREATE_PROPERTY_ERROR = 'CREATE_PROPERTY_ERROR'

export const READ_PROPERTIES_BEGIN = 'READ_PROPERTIES_BEGIN'
export const READ_PROPERTIES_SUCCESS = 'READ_PROPERTIES_SUCCESS'
export const READ_PROPERTIES_ERROR = 'READ_PROPERTIES_ERROR'

export const UPDATE_PROPERTY_BEGIN = 'UPDATE_PROPERTY_BEGIN'
export const UPDATE_PROPERTY_SUCCESS = 'UPDATE_PROPERTY_SUCCESS'
export const UPDATE_PROPERTY_ERROR = 'UPDATE_PROPERTY_ERROR'

//---- unit -----//
export const CREATE_UNIT_BEGIN = 'CREATE_UNIT_BEGIN'
export const CREATE_UNIT_SUCCESS = 'CREATE_UNIT_SUCCESS'
export const CREATE_UNIT_ERROR = 'CREATE_UNIT_ERROR'

export const READ_UNITS_BEGIN = 'READ_UNITS_BEGIN'
export const READ_UNITS_SUCCESS = 'READ_UNITS_SUCCESS'
export const READ_UNITS_ERROR = 'READ_UNITS_ERROR'
//---- single unit -----//
export const GET_UNIT_BEGIN = 'GET_UNIT_BEGIN'
export const GET_UNIT_SUCCESS = 'GET_UNIT_SUCCESS'
export const GET_UNIT_ERROR = 'GET_UNIT_ERROR'

export const UPDATE_UNIT_BEGIN = 'UPDATE_UNIT_BEGIN'
export const UPDATE_UNIT_SUCCESS = 'UPDATE_UNIT_SUCCESS'
export const UPDATE_UNIT_ERROR = 'UPDATE_UNIT_ERROR'

export const DELETE_UNIT_BEGIN = 'DELETE_UNIT_BEGIN'
export const DELETE_UNIT_SUCCESS = 'DELETE_UNIT_SUCCESS'
export const DELETE_UNIT_ERROR = 'DELETE_UNIT_ERROR'

//---- tenant -----//
export const CREATE_TENANT_BEGIN = 'CREATE_TENANT_BEGIN'
export const CREATE_TENANT_SUCCESS = 'CREATE_TENANT_SUCCESS'
export const CREATE_TENANT_ERROR = 'CREATE_TENANT_ERROR'

export const READ_TENANTS_BEGIN = 'READ_TENANTS_BEGIN'
export const READ_TENANTS_SUCCESS = 'READ_TENANTS_SUCCESS'
export const READ_TENANTS_ERROR = 'READ_TENANTS_ERROR'

export const UPDATE_TENANT_BEGIN = 'UPDATE_TENANT_BEGIN'
export const UPDATE_TENANT_SUCCESS = 'UPDATE_TENANT_SUCCESS'
export const UPDATE_TENANT_ERROR = 'UPDATE_TENANT_ERROR'

//---- payments -----//
export const CREATE_EXPENSE_BEGIN = 'CREATE_EXPENSE_BEGIN'
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS'
export const CREATE_EXPENSE_ERROR = 'CREATE_EXPENSE_ERROR'

export const READ_EXPENSES_BEGIN = 'READ_EXPENSES_BEGIN'
export const READ_EXPENSES_SUCCESS = 'READ_EXPENSES_SUCCESS'
export const READ_EXPENSES_ERROR = 'READ_EXPENSES_ERROR'

export const READ_REQUESTS_BEGIN = 'READ_REQUESTS_BEGIN'
export const READ_REQUESTS_SUCCESS = 'READ_REQUESTS_SUCCESS'
export const READ_REQUESTS_ERROR = 'READ_REQUESTS_ERROR'

export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const READ_MESSAGES_BEGIN = 'READ_MESSAGES_BEGIN'
export const READ_MESSAGES_SUCCESS = 'READ_MESSAGES_SUCCESS'
export const READ_MESSAGES_ERROR = 'READ_MESSAGES_ERROR'