export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_REQUEST_BEGIN = 'CREATE_REQUEST_BEGIN';
export const CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS';
export const CREATE_REQUEST_ERROR = 'CREATE_REQUEST_ERROR';

export const CREATE_PROPERTY_BEGIN = 'CREATE_PROPERTY_BEGIN'
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS'
export const CREATE_PROPERTY_ERROR = 'CREATE_PROPERTY_ERROR'

export const READ_PROPERTIES_BEGIN = 'READ_PROPERTIES_BEGIN'
export const READ_PROPERTIES_SUCCESS = 'READ_PROPERTIES_SUCCESS'
export const READ_PROPERTIES_ERROR = 'READ_PROPERTIES_ERROR'

export const CREATE_TENANT_BEGIN = 'CREATE_TENANT_BEGIN'
export const CREATE_TENANT_SUCCESS = 'CREATE_TENANT_SUCCESS'
export const CREATE_TENANT_ERROR = 'CREATE_TENANT_ERROR'

export const READ_TENANTS_BEGIN = 'READ_TENANTS_BEGIN'
export const READ_TENANTS_SUCCESS = 'READ_TENANTS_SUCCESS'
export const READ_TENANTS_ERROR = 'READ_TENANTS_ERROR'

export const CREATE_UNIT_BEGIN = 'CREATE_UNIT_BEGIN'
export const CREATE_UNIT_SUCCESS = 'CREATE_UNIT_SUCCESS'
export const CREATE_UNIT_ERROR = 'CREATE_UNIT_ERROR'

export const READ_UNITS_BEGIN = 'READ_UNITS_BEGIN'
export const READ_UNITS_SUCCESS = 'READ_UNITS_SUCCESS'
export const READ_UNITS_ERROR = 'READ_UNITS_ERROR'

export const CREATE_PAYMENT_BEGIN = 'CREATE_PAYMENT_BEGIN'
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS'
export const CREATE_PAYMENT_ERROR = 'CREATE_PAYMENT_ERROR'

export const READ_PAYMENTS_BEGIN = 'READ_PAYMENTS_BEGIN'
export const READ_PAYMENTS_SUCCESS = 'READ_PAYMENTS_SUCCESS'
export const READ_PAYMENTS_ERROR = 'READ_PAYMENTS_ERROR'

export const CREATE_RENT_BEGIN = 'CREATE_RENT_BEGIN'
export const CREATE_RENT_SUCCESS = 'CREATE_RENT_SUCCESS'
export const CREATE_RENT_ERROR = 'CREATE_RENT_ERROR'

export const READ_RENTS_BEGIN = 'READ_RENTS_BEGIN'
export const READ_RENTS_SUCCESS = 'READ_RENTS_SUCCESS'
export const READ_RENTS_ERROR = 'READ_RENTS_ERROR'